version: "3.8"

services:
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'mypass123'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: "mysql-app"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    depends_on:
      - db
    ports:
      - "8081:80"
    links:
      - db

volumes:
  mysql-data:
